Added comments, cleaned up the code a bit and updated README
marekpridal/BarChart pull request #4
Opened 2020-10-17 21:50 UTC by paulpela

2020-10-17 22:01 UTC, marekpridal commented
Thanks a lot for contribution! I'll take a look as soon as possible 🙂

2020-10-18 08:36 UTC, marekpridal requested changes
Thanks a lot for improving documentation and code cleanest! I added few comments. Also I noticed GitHub Actions seems to be disabled in you profile and because of that the CI check cannot pass. Can you please enable it to be sure, everything works as expected?

2020-10-18 08:36 UTC, marekpridal commented on Sources/BarChartKit/SwiftUI/BarChart.swift
>          public struct DataElement: Equatable, Identifiable {
Move please conformance of protocols to extensions where implementation is.

2020-10-18 08:36 UTC, marekpridal commented on Sources/BarChartKit/SwiftUI/BarChart.swift
> +extension BarChart.DataSet.DataElement {
Make extensions public, too.

2020-10-18 21:44 UTC, paulpela commented
Hi, I fixed conformance locations and added public wherever needed, however I can't fix the checks issue. Actions are definitely enabled on my repository. Any ideas?

2020-10-18 21:56 UTC, paulpela commented
Looks like it worked now! Sorry for the mess! I learned a lot here :)

2020-10-19 07:23 UTC, marekpridal approved these changes
Thanks a lot for update!

2020-10-19 07:24 UTC, merged